{{- if .Values.filebeat.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-filebeat-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  ELASTICSEARCH_HOST: {{ .Values.filebeat.elasticsearch.host | quote }}
  ELASTICSEARCH_USERNAME: {{ .Values.filebeat.elasticsearch.username | quote }}
  ELASTICSEARCH_PASSWORD: {{ .Values.filebeat.elasticsearch.password | quote }}
  KIBANA_HOST: {{ .Values.filebeat.kibana.host | quote }}
  KIBANA_USERNAME: {{ .Values.filebeat.kibana.username | quote }}
  KIBANA_PASSWORD: {{ .Values.filebeat.kibana.password | quote }}
{{- end }} 