{{- if .Values.filebeat.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.filebeat.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  ELASTICSEARCH_HOST: {{ .Values.filebeat.elasticsearch.host | quote }}
  ELASTICSEARCH_USERNAME: {{ .Values.filebeat.elasticsearch.username | quote }}
  ELASTICSEARCH_PASSWORD: {{ .Values.filebeat.elasticsearch.password | quote }}
{{- end }} 