apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config-prod
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.configLabels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:mysql://mysql-prod-service:3306/project2-prod
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect 