apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.workloadLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "common.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: /config
        envFrom:
        - secretRef:
            name: {{ include "common.fullname" . }}-db-secret-{{ .Values.spring.profiles.active }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.spring.profiles.active }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "common.fullname" . }}-config-{{ .Values.spring.profiles.active }} 