apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-db-secret-dev
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.configLabels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.db.dev.username | b64enc }}
  DB_PASSWORD: {{ .Values.db.dev.password | b64enc }} 