apiVersion: v2
name: project1
description: A Helm chart for project1
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common 