apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  database.url: {{ .Values.secret.database.url | b64enc | quote }}
  database.username: {{ .Values.secret.database.username | b64enc | quote }}
  database.password: {{ .Values.secret.database.password | b64enc | quote }} 