apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-db-secret-prod
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.db.prod.username | b64enc }}
  DB_PASSWORD: {{ .Values.db.prod.password | b64enc }} 