# Application name settings
nameOverride: "project2"
fullnameOverride: "project2-prod"
namespace: "project2-prod"

# Environment type
environment: "prod"

# Deployment settings
deployment:
  resources:
    request:
      cpu: 500m
      mem: 1Gi
    limit:
      cpu: 2000m
      mem: 4Gi
  replicas: 3
  containerPort: 8022
  protocol: TCP
  runAsUser: 1000
  runAsGroup: 1000

# Image settings
image:
  repository: "076248830837.dkr.ecr.ap-northeast-2.amazonaws.com/project2-prod"
  tag: "1.0.0"
  pullPolicy: Always
  secretName: "ap-northeast-2-ecr-registry"

# Service settings
service:
  port: 8022
  targetPort: 8022
  type: ClusterIP

# Filebeat settings
filebeat:
  enabled: true
  image: elastic/filebeat:7.17.2
  configMapName: "project2-filebeat-config"
  secretName: "project2-filebeat-secret"

# Node selector
nodeSelector:
  type: "prod"

spring:
  profiles:
    active: prod

db:
  dev:
    username: ""
    password: ""
  prod:
    username: "prod_user"
    password: "prod_password" 