# Application name settings
nameOverride: "project1"
namespace: "project1-dev"

# Environment type
environment: "dev"

# Deployment settings
deployment:
  resources:
    request:
      cpu: 100m
      mem: 256Mi
    limit:
      cpu: 500m
      mem: 1Gi
  replicas: 1
  containerPort: 8021
  protocol: TCP
  runAsUser: 1000
  runAsGroup: 1000

# Image settings
image:
  repository: "076248830837.dkr.ecr.ap-northeast-2.amazonaws.com/project1"
  tag: "1.0.0"
  pullPolicy: Always
  secretName: "ap-northeast-2-ecr-registry"

# Service settings
service:
  port: 8021
  targetPort: 8021
  type: ClusterIP

# Filebeat settings
filebeat:
  enabled: true
  image: elastic/filebeat:7.17.2
  configMapName: "project1-filebeat-config"
  secretName: "project1-filebeat-secret"

# Node selector
nodeSelector:
  type: "dev"

spring:
  profiles:
    active: dev

db:
  dev:
    username: "dev_user"
    password: "dev_password"
  prod:
    username: ""
    password: "" 